/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/studioTheme.ts
 * Command: astryx theme build src/theme/studioTheme.ts --out src/styles/studio-theme.css
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const studioTheme: DefinedTheme;
