/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/studioTheme.ts
 * Command: astryx theme build src/theme/studioTheme.ts --out src/styles/studio-theme.css
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

/**
 * studio theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { studioTheme } from './studio';
 *   import './studio.css';
 */
export const studioTheme = {
  name: 'studio',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5625rem",
    "--font-size-xs": "0.6875rem",
    "--font-size-sm": "0.875rem",
    "--font-size-base": "1.0625rem",
    "--font-size-lg": "1.3125rem",
    "--font-size-xl": "1.6875rem",
    "--font-size-2xl": "2.0625rem",
    "--font-size-3xl": "2.625rem",
    "--font-size-4xl": "3.25rem",
    "--font-size-5xl": "4.0625rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-semibold)",
    "--text-heading-1-leading": "1.2121",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.3333",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "700",
    "--text-heading-3-leading": "1.3333",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "700",
    "--text-heading-4-leading": "1.4118",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "700",
    "--text-heading-5-leading": "1.4286",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "700",
    "--text-heading-6-leading": "1.4545",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.4118",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.3333",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.4118",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.4118",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.4286",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2308",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2308",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.2381",
    "--duration-fast-min": "110ms",
    "--duration-fast": "140ms",
    "--duration-fast-max": "175ms",
    "--duration-medium-min": "210ms",
    "--duration-medium": "260ms",
    "--duration-medium-max": "325ms",
    "--duration-slow-min": "415ms",
    "--duration-slow": "520ms",
    "--duration-slow-max": "650ms",
    "--font-family-body": "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-heading": "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-code": "\"JetBrains Mono\", \"SF Mono\", Monaco, Consolas, monospace",
    "--color-accent": "#4690FF",
    "--color-accent-muted": "#4690FF33",
    "--color-neutral": "#FFFFFF1A",
    "--color-background-surface": "#0A0A0B",
    "--color-background-body": "#000000",
    "--color-overlay": "#000000E6",
    "--color-overlay-hover": "#FFFFFF14",
    "--color-overlay-pressed": "#FFFFFF24",
    "--color-background-muted": "#141416",
    "--color-text-primary": "#FFFFFF",
    "--color-text-secondary": "#A8ADB5",
    "--color-text-disabled": "#6A6F78",
    "--color-text-accent": "#4690FF",
    "--color-on-dark": "#FFFFFF",
    "--color-on-light": "#000000",
    "--color-on-accent": "#001B3D",
    "--color-on-success": "#001B0A",
    "--color-on-error": "#3D0008",
    "--color-on-warning": "#2E2000",
    "--color-icon-accent": "#4690FF",
    "--color-icon-primary": "#FFFFFF",
    "--color-icon-secondary": "#A8ADB5",
    "--color-icon-disabled": "#6A6F78",
    "--color-background-card": "#101014",
    "--color-background-popover": "#16161A",
    "--color-background-inverted": "#FFFFFF",
    "--color-success": "#2ECC71",
    "--color-success-muted": "#2ECC7133",
    "--color-error": "#FF4D5E",
    "--color-error-muted": "#FF4D5E33",
    "--color-warning": "#FFC63D",
    "--color-warning-muted": "#FFC63D33",
    "--color-border": "#FFFFFF1F",
    "--color-border-emphasized": "#2A2A30",
    "--color-skeleton": "#1C1C21",
    "--color-track": "#1C1C21",
    "--color-shadow": "#000000B3",
    "--color-tint-hover": "white",
    "--color-background-blue": "#4690FF",
    "--color-border-blue": "#4690FF",
    "--color-icon-blue": "#4690FF",
    "--color-text-blue": "#9CC4FF",
    "--color-background-cyan": "#22D3EE",
    "--color-border-cyan": "#0891B2",
    "--color-icon-cyan": "#22D3EE",
    "--color-text-cyan": "#67E8F9",
    "--color-background-gray": "#1F1F25",
    "--color-border-gray": "#3A3A42",
    "--color-icon-gray": "#A8ADB5",
    "--color-text-gray": "#D4D7DD",
    "--color-background-green": "#2ECC71",
    "--color-border-green": "#1E9E55",
    "--color-icon-green": "#2ECC71",
    "--color-text-green": "#7BE8AC",
    "--color-background-orange": "#FF9F45",
    "--color-border-orange": "#C86A17",
    "--color-icon-orange": "#FF9F45",
    "--color-text-orange": "#FFC48F",
    "--color-background-pink": "#F472B6",
    "--color-border-pink": "#BE3D86",
    "--color-icon-pink": "#F472B6",
    "--color-text-pink": "#FBAED3",
    "--color-background-purple": "#A78BFA",
    "--color-border-purple": "#6D4BD1",
    "--color-icon-purple": "#A78BFA",
    "--color-text-purple": "#C9B6FD",
    "--color-background-red": "#FF4D5E",
    "--color-border-red": "#C22A3A",
    "--color-icon-red": "#FF4D5E",
    "--color-text-red": "#FFA3AC",
    "--color-background-teal": "#2DD4BF",
    "--color-border-teal": "#0F8F80",
    "--color-icon-teal": "#2DD4BF",
    "--color-text-teal": "#7CE8DC",
    "--color-background-yellow": "#FFC63D",
    "--color-border-yellow": "#B98D14",
    "--color-icon-yellow": "#FFC63D",
    "--color-text-yellow": "#FFDD8F",
    "--radius-none": "0px",
    "--radius-inner": "0.5rem",
    "--radius-element": "0.75rem",
    "--radius-container": "1.25rem",
    "--radius-page": "1.75rem",
    "--radius-full": "9999px",
    "--shadow-low": "0 2px 8px #00000066",
    "--shadow-med": "0 4px 16px #00000080",
    "--shadow-high": "0 12px 32px #00000099",
    "--shadow-inset-hover": "inset 0px 0px 0px 1px #FFFFFF26",
    "--shadow-inset-selected": "inset 0px 0px 0px 2px #4690FF66",
    "--shadow-inset-success": "inset 0px 0px 0px 1px #2ECC7159",
    "--shadow-inset-warning": "inset 0px 0px 0px 1px #FFC63D59",
    "--shadow-inset-error": "inset 0px 0px 0px 1px #FF4D5E59"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "base": {
        "borderRadius": "var(--radius-element)",
        "fontWeight": "600"
      },
      "variant:primary": {
        "backgroundColor": "#4690FF",
        "color": "var(--color-on-accent)"
      },
      "variant:secondary": {
        "backgroundColor": "#1C1C21",
        "color": "var(--color-text-primary)",
        "borderColor": "var(--color-border-emphasized)"
      },
      "variant:ghost": {
        "color": "var(--color-text-primary)"
      },
      "variant:destructive": {
        "backgroundColor": "var(--color-error)",
        "color": "var(--color-on-error)"
      }
    },
    "card": {
      "base": {
        "borderRadius": "var(--radius-container)",
        "borderColor": "var(--color-border)"
      }
    },
    "field": {
      "base": {
        "borderRadius": "var(--radius-element)"
      }
    },
    "banner": {
      "base": {
        "borderRadius": "var(--radius-container)"
      },
      "status:info": {
        "backgroundColor": "#4690FF1F",
        "--color-text-primary": "var(--color-text-blue)",
        "--color-text-secondary": "var(--color-text-blue)"
      },
      "status:success": {
        "backgroundColor": "#2ECC711F",
        "--color-text-primary": "var(--color-text-green)",
        "--color-text-secondary": "var(--color-text-green)"
      },
      "status:warning": {
        "backgroundColor": "#FFC63D1F",
        "--color-text-primary": "var(--color-text-yellow)",
        "--color-text-secondary": "var(--color-text-yellow)"
      },
      "status:error": {
        "backgroundColor": "#FF4D5E1F",
        "--color-text-primary": "var(--color-text-red)",
        "--color-text-secondary": "var(--color-text-red)"
      }
    },
    "badge": {
      "base": {
        "borderRadius": "var(--radius-full)",
        "fontWeight": "600"
      },
      "variant:info": {
        "backgroundColor": "#4690FF26",
        "color": "var(--color-text-blue)"
      },
      "variant:success": {
        "backgroundColor": "#2ECC7126",
        "color": "var(--color-text-green)"
      },
      "variant:warning": {
        "backgroundColor": "#FFC63D26",
        "color": "var(--color-text-yellow)"
      },
      "variant:error": {
        "backgroundColor": "#FF4D5E26",
        "color": "var(--color-text-red)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": []
  },
  __axes: {
    "typography": {
      "scale": {
        "base": 17,
        "ratio": 1.25
      },
      "body": {
        "family": "Inter",
        "fallbacks": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif"
      },
      "heading": {
        "family": "Inter",
        "fallbacks": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
        "weights": {
          "3": "700",
          "4": "700",
          "5": "700",
          "6": "700"
        }
      },
      "code": {
        "family": "JetBrains Mono",
        "fallbacks": "\"SF Mono\", Monaco, Consolas, monospace"
      }
    },
    "motion": {
      "fast": 140,
      "medium": 260,
      "slow": 520,
      "ratio": 0.8
    }
  },

};
